Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/cart/urls.py
#from django.urls import path
#from cart import views
#app_name="cart"


#urlpatterns = [
 #   path('add_cart/<int:p>', views.add_cart,name="add_cart"),
 #   path('cart_view',views.cart_view,name="cart_view"),
 #   path('cart_remove/<int:p>',views.cart_remove,name="cart_remove"),
 #   path('full_remove/<int:p>',views.full_remove,name="full_remove"),
 #   path('orderform/<float:p>',views.order,name="orderform"),
#]

from django.urls import path
from cart import views

app_name = "cart"

urlpatterns = [
    path('add_cart/<int:p>/', views.add_cart, name="add_cart"),
    path('cart_view/', views.cart_view, name="cart_view"),
    path('cart_remove/<int:p>/', views.cart_remove, name="cart_remove"),
    path('full_remove/<int:p>/', views.full_remove, name="full_remove"),
    path('orderform/', views.order, name="orderform"),
    path('orderview/', views.orderview, name="orderview"),
]

Ecommerce/search/urls.py
from django.urls import path
from search import views
app_name="search"


urlpatterns = [
    path('searchresult/', views.searchresult,name="searchresult"),
]

Ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"


urlpatterns = [

    path('', views.allProdCat,name="allprodcat"),
    path('allproducts/<slug:cslug>',views.allproducts,name="allproducts"),
    path('prodetails/<slug:pslug>', views.prodetail,name="prodetail"),

    path('reg/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),

]

Ecommerce/cart/models.py
from django.db import models

from shop.models import Product


from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Cart(models.Model):
    DoesNotExist = None
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    date_added=models.DateField(auto_now_add=True)
    quantity=models.IntegerField(default=1)
    active=models.BooleanField(default=True)
    def subtotal(self):
        return self.quantity * self.products.price

    def __str__(self):
        return self.products.name

# self.quantity= quantity of current object


# TABLE "accounts"  --> for getting payment and account details  (normally gateway will use)

class Account(models.Model):
    objects = None
    acctnumber=models.CharField(max_length=200)
    acctype=models.CharField(max_length=200)
    amount=models.IntegerField()

    def __str__(self):
        return self.acctnumber


# TABLE "order"  -->  for storing order details

class Order(models.Model):
    objects = None
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone= models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="Pending")          # after payment status become "completed"
    delivery_status=models.CharField(max_length=30,default="Pending")       # after delivery status become "completed"
    noofitems=models.IntegerField()

    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


    def subtotal(self):
        return self.noofitems * self.products.price

# auto_now_add=True -->capture and store the timestamp of when an object was created

Ecommerce/search/models.py
from django.db import models

# Create your models here.

Ecommerce/cart/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart

from cart.models import Cart,Account,Order
from django.shortcuts import redirect

from django.contrib import messages
from django.http import HttpResponse

from django.shortcuts import render
from .models import Cart, Account, Order

# VIEW FOR CART (view connects to cart.html)

@login_required
def cart_view(request):
     total=0
     try:
          user=request.user
          cart=Cart.objects.filter(user=user)
          for i in cart:                        # i= each cart object
               total+=i.quantity * i.products.price
     except Cart.DoesNotExist:                  # if the object is not there
          pass
     return render(request,'cart.html',{'cart':cart,'total':total})


# VIEW FOR ADD TO CART

@login_required
def add_cart(request,p):
     product=Product.objects.get(id=p)           # product detail of particular product "p" to be added
     user=request.user                          # user info
     try:
          cart=Cart.objects.get(products=product,user=user) # if same "prod & user" (object) is there
          if cart.quantity < cart.products.stock:
               cart.quantity+=1
          cart.save()
     except Cart.DoesNotExist:
          cart=Cart.objects.create(products=product,user=user,quantity=1)
          cart.save()

     return redirect('cart:cart_view')


# @login_required =decorator is used in Django to restrict access to a view function only authenticated users.
# render = connect to "html"
# redirect= to connect to "view"


# VIEW FOR "-" IN  CART

@login_required
def cart_remove(request,p):
     user = request.user
     product = Product.objects.get(id=p)
     try:
          cart = Cart.objects.get(products=product, user=user)
          if cart.quantity > 1:
               cart.quantity-=1
               cart.save()
          else:
               cart.delete()

     except:
          pass
     return redirect('cart:cart_view')


#quantity=0 , means, entire row will get deleted


# VIEW FOR "full_remove/trash" IN  CART

@login_required
def full_remove(request,p):
     user = request.user
     product = Product.objects.get(id=p)
     try:
          cart = Cart.objects.get(products=product, user=user)
          cart.delete()
     except:
          pass

     return redirect('cart:cart_view')



# VIEW FOR "orderform/place order" IN  CART
# (get values of -->Address,Ph_no,Acct_no )

@login_required
def order(request):
     total=0
     items=0
     msg=0
     if(request.method=="POST"):
          a=request.POST['a']
          p=request.POST['p']
          num=request.POST['num']
          user=request.user
          cart=Cart.objects.filter(user=user)

          for i in cart:
               total+=i.quantity*i.products.price
               items+=i.quantity
          ac=Account.objects.get(acctnumber=num)
          if float(ac.amount) >= total:
                    ac.amount=ac.amount - total
                    ac.save()
                    for i in cart:             # to add details to Order table
                         o=Order(user=user,products=i.products,address=a,phone=p,order_status="paid",noofitems=i.quantity)
                         o.save()
                    cart.delete()
                    msg="Order Placed Successfully"
                    return render(request,'orderdetail.html',{'msg':msg,'total':total,'items':items})
          else:
                    msg = "Insufficent Amount.You can't Place Order"
                    return render(request, 'orderdetail.html',{'msg':msg})

     return render(request,'orderform.html')


# try = if exception comes, it will prevent from stop checking whether an object is present/not
#  p --> p= total_amt in the cart, a.amount= amt already have
# a.amount=a.amount -p      --> updated the new amount in a.amount

# to find number of items(quantity)



# VIEW FOR "orderview" IN  CART


@login_required
def orderview(request):
     user=request.user
     o=Order.objects.filter(user=user,order_status="paid")
     return render(request,'orderview.html',{'o':o,'name':user.username})

Ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

from django.http import HttpResponse
# Create your views here.

# VIEW TO SEARCH  PRODUCTS
def searchresult(request):
    products=None  # while searching prods, if we are not giving any keywords and click, it will shows Prod as "None"
    if request.method=="POST":
        query=request.POST.get('q') # getting the keyword here
        if query:
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'products':products})


# filter =to get only some elements
# Q object is used to create complex queries by combining multiple conditions with logical operators.

Ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!--css link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--js link-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!--external css link-->
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
    <!--google font link-->
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Indie+Flower&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <!--google----------- font-awesome link (for icons)-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <!-- font-awesome cdn -->  <!-- ? -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">



</head>
<body>
     <!-- to give logo img -->
      <div class="container-fluid">
          <header>
          <center><img src="{% static 'img/logo.jpg' %}" height="150px" width="150px" ></center>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
        </li>

        <!--<li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> -->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">All Categories</a></li>
              {% for i in links %}  <!-- links of category -->
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
                                         <!--href= ref from  category.html -->
              {% endfor %}
            <!--<li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li> -->
          </ul>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> -->

  {% if user.is_authenticated %}

  <li>
             <li class="nav-item">
          <a class="nav-link " href="{% url 'shop:logout' %}">Logout</a>
      </li>

          <li>
             <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_view' %}"><i class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
      </li>


          <li>
             <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:orderview' %}">Your Orders</a>
      </li>

 {% else %}

       <li>
             <li class="nav-item">
          <a class="nav-link " href="{% url 'shop:register' %}">Register</a>
      </li>

           <li>
             <li class="nav-item">
          <a class="nav-link " href="{% url 'shop:login' %}">Login</a>
      </li>

 {% endif %}

      </ul>
      <form class="d-flex justify-content-" action="{% url 'search:searchresult' %}" method="POST">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>



    </div>
  </div>
  </nav>
  </header>

             {% block content %}
             {% endblock %}

         <!-- <footer style="position:absolute;bottom:0;" class="footer">
               <div>
                 <p><i class="fa-regular fa-copyright"></i>Myshop pvt ltd.All rights reserved </p>
               </div>
          </footer>  -->

          <footer class="footer">
    <div>
        <p><i class="fa-regular fa-copyright"></i>Myshop pvt ltd. All rights reserved</p>
    </div>
          </footer>




      </div>

</body>
</html>

Ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %} cart {% endblock %}
{% block content %}

<div class="container-fluid" style="margin-bottom:100px">
{% if not cart %}
    <div>
        <h1 class="text-center"> Cart is Empty</h1>
    </div>

    <!--<div>
        <strong><a href="{% url 'shop:allprodcat' %}">Continue Shopping </a></strong>
        <!--<button class="btn btn-primary" href="{% url 'shop:allprodcat' %}">Continue Shopping</button> -->
        <!--<a class="btn btn-primary" href="{% url 'shop:allprodcat' %}">Continue Shopping</a>-->
       <!--<button class="btn btn-primary custom-button" href="{% url 'shop:allprodcat' %}">Continue Shopping</button>

    </div>  -->

    {% else %}
    <div class="row mx-auto">
        <h2 style="width:100%;">Shopping Cart</h2>

        <div class="col-sm-6">
            <table class="table">

                <tr>

                <th colspan="5" class="text-center">
                    YOUR ITEMS
                </th> </tr>
                {% for i in cart %}
                <tr>
                    <td><img src="{{i.products.image.url}}" style="height:150px; width:150px;"></td>

                    <td>{{i.products.name}}</td>
                    <td>
                    Pid:{{i.products.id}} <br>
                    UnitPrice:{{i.products.price}} <br>
                    Quantity:{{i.quantity}} * {{i.products.price}} <br>
                    </td>

                    <td> SubTotal:{{i.subtotal}}</td>
                    {% if i.quantity < i.products.stock %}
                         <!-- if quantity is less than product stock,then only can add (+)-->
                    <td><a href="{% url 'cart:add_cart' i.products.id %}"><i class="fa-solid fa-plus custom_icon"></i></a>
                                   <!--link given as detail.html-->
                        <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-minus custom_icon"></i></a>
                        <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-solid fa-trash custom_icon"></i></a>  </td>

                    {% else %}
                    <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-minus custom_icon"></i></a>
                    <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-solid fa-trash custom_icon"></i></a>
                    {% endif %}
                </tr>

                {% endfor %}
            </table>
        </div>
        {% endif %}
          <div class="col-sm-6">
              <table class="table table-bordered">

                 <tr><th colspan="5" class="text-center">CHECKOUT</th></tr>
                  <tr><th style="text-align:right;">TOTAL PRICE:&nbsp;&nbsp;&nbsp;&nbsp;{{total}}</th></tr>
              </table>

          <a class="btn btn-primary" href="{% url 'shop:allprodcat' %}">Continue shopping</a>
          <a class="btn btn-primary" href="{% url 'cart:orderform' %}">Place Order</a>




              <!-- <a class="btn btn-primary" href="{% url 'shop:allprodcat' %}">Button Text</a> -->
          </div>
    </div>
</div>

{% endblock %}

Ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} category {% endblock %}
{% block content %}

<!--banner img-->
<div>
    <img src="{% static 'img/banner.jpg' %}" height="450px" width="100%">
</div>
<!--heading and desc-->
<div style="margin-bottom:100px;">
    <h1 class="text-center">Our collections</h1>
    <p class="text-justify text-padding">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<!--cards-->
<div class="container" style="margin-bottom:100px;">
    <div class="row mx-auto">
        {% for i in c %}
        <div class="col-sm-4">
            <!--bootstrap 5/card-->
            <div class="card" style="width: 20rem; display: flex; flex-direction: column; justify-content: center;">
                <img src="{{i.image.url}}" class="card-img-top" alt="{{i.image}}" style="height: 200px; object-fit: cover;">
                <div class="card-body text-center">
                    <h5 class="card-title title_heading">{{i.name}}</h5>
                    <!--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                    <!-- description going to give inside detail page of Product-->
                    <a href="{% url 'shop:allproducts' i.slug %}" class="btn btn-primary link">PRODUCTS</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

Ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} product detail {% endblock %}
{% block content %}

<div class=container">
    <div class="row">
        <div class="col-sm-6">
            <img src="{{p.image.url}}" height="400px" width="450px" alt="{{p.image.url}}">
        </div>
        <div class="col-sm-6 mt-5">
            <div>
                <h1>{{p.name}}</h1>
                <p>{{p.price}}</p>
                <h3>PRODUCT DESCRIPTION</h3>
                <p>{{p.description}}</p>
                {% if p.stock <= 0 %}
                <h2>OUT OF STOCK</h2>
                {% else %}
                <a class="btn btn-primary" href="{% url 'cart:add_cart' p.id %}">ADD TO CART</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} login {% endblock %}
{% block content %}
<h1> Login</h1>

<form method="POST">
    {% csrf_token%}
    <div class="mb-3">
  <label  class="form-label">User Name</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>


  <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>


     <div class="mb-3">

  <input type="submit" class="form-control">
     </div>

    {% if messages %}
    {% for i in  messages %}
    <ul class="messages">
       <li>{{i}}</li>
    </ul>
{% endfor %}
{% endif %}
</form>
{% endblock %}

Ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} order detail page {% endblock %}
{% block content %}
<center>
<div class="container" style="margin-bottom:100px;">
    <h1 class="text-success"> Your Order Placed Successfully </h1>
    <p> Thank You.....</p>
    <a class="btn-danger" href="{% url 'shop:allprodcat' %}">Continue Shopping</a>
    {{total}}
    {{msg}}
    {{items}}
</div>
</center>

{% endblock %}

Ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block title %} order form page {% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Address</label>
        <textarea class="form-control" placeholder="Enter Address" name="a" rows="3"></textarea>
      </div>

    <div class="mb-3">
        <label class="form-label">Phone Number</label>
        <input type="text" class="form-control" name="p" placeholder="Enter Phone Number">
      </div>

    <div class="mb-3">
        <label class="form-label">Account Number</label>
        <input type="text" class="form-control" name="num" placeholder="Enter Account Number">
      </div>

    <div class="mb-3">
        <input type="submit" class="btn btn-primary" value="Submit">
      </div>

</form>

{% endblock %}

Ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Order View Page{% endblock %}

{% block content %}
<div class="container" style="margin-bottom:150px;">
    <div class="row">
        <h3>Name of the Customer: {{ name }}</h3>
        {% for p in o %}
        <div class="col-sm-5" style="border:1px solid black;">
            <img src="{{ p.products.image.url }}" height="200px" width="200px" alt="{{ p.products.image.url }}">
        </div>

        <div class="col-sm-5" style="border:1px solid black;">
                Delivery Address: {{ p.address }}<br>
                Phone Number: {{ p.phone }}<br>
                {{ p.products.name }}<br>
                {{ p.products.price }}<br>
                quantity ordered:{{p.noofitems}}<br>
                <!--<p>{{ order.noofitems }}</p> -->
                Subtotal: {{ p.subtotal }}<br>
                Ordered on {{ p.date_added }}<br>

                <strong class="text-primary">Delivered on {{p.date_added}}</strong><br>
                <strong class="text-success">Delivery Status: {{p.delivery_status}}</strong><br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block title %} products {% endblock %}
{% block content %}

<!--banner img-->
<div>
    <img src="{{c.image.url}}" height="450px" width="100%">
</div>
<!--heading and desc-->
<div style="margin-bottom:100px;">
    <h1 class="text-center">{{c.name}}</h1>
    <p class="text-justify text-padding"></p>
</div>
<!--cards-->
<div class="container" style="margin-bottom:100px;">
    <div class="row mx-auto">
        {% for i in p %}
        <div class="col-sm-4">
            <!--bootstrap 5/card-->
            <div class="card" style="width: 20rem; display: flex; flex-direction: column; justify-content: center;">
                <img src="{{i.image.url}}" class="card-img-top" alt="" style="height: 200px; object-fit: cover;">
                <div class="card-body text-center">
                    <h5 class="card-title title_heading">{{i.name}}</h5>
                    <!--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                    <!-- description going to give inside detail page of Product-->
                    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary link">DETAILS</a>
                </div>
            </div>
        </div>
     {% endfor %}
    </div>
</div>

{% endblock %}

Ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} sign up {% endblock %}
{% block content %}
  <div class="container">
    <h1>Sign Up</h1>

    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label class="form-label">User Name</label>
        <input type="text" class="form-control" name="u" placeholder="Enter username">
      </div>

      <div class="mb-3">
        <label class="form-label">First Name</label>
        <input type="text" class="form-control" name="f" placeholder="Enter firstname">
      </div>

      <div class="mb-3">
        <label class="form-label">Last Name</label>
        <input type="text" class="form-control" name="l" placeholder="Enter lastname">
      </div>

      <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" name="e" placeholder="Enter email">
      </div>

      <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter password">
      </div>

      <div class="mb-3">
        <label class="form-label">Confirm Password</label>
        <input type="password" class="form-control" name="cp" placeholder="Enter confirm password">
      </div>

      <div class="mb-3">
        <input type="submit" class="btn btn-primary" value="Submit">
      </div>
    </form>
  </div>
{% endblock %}

Ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %} search {% endblock %}
{% block content %}

<center>
 <div>
     <h3>You Have Searched For {{query}} </h3> <!-- {{query}}=keyword we have given -->
 </div>
</center>

<!--cards-->
<div class="container" style="margin-bottom:100px;">
    <div class="row mx-auto">
        {% for i in products %}
        <div class="col-sm-4">
            <!--bootstrap 5/card-->
            <div class="card" style="width: 20rem; display: flex; flex-direction: column; justify-content: center;">
                <img src="{{i.image.url}}" class="card-img-top" alt="" style="height: 200px; object-fit: cover;">
                <div class="card-body text-center">
                    <h5 class="card-title title_heading">{{i.name}}</h5>
                    <!--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                    <!-- description going to give inside detail page of Product-->
                    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary link">DETAILS</a>
                </div>
            </div>
        </div>
        {% empty %}  <!-- if product is empty -->
        <div>
            <p>0 RESULTS FOUND</p>
        </div>

     {% endfor %}
    </div>
</div>

{% endblock %}